### ISSUE TITLE
compute_feature.py code won't work on other system

### ISSUE THREAD

**Issue by khalibartan** [ashishchopra778/Matching-Geotagged-Images#1]
@ashishchopra778 Can you update this [line](https://github.com/ashishchopra778/Matching-Geotagged-Images/blob/master/compute_feature.py#L11) and line next to it according to local file structure of repository rather than your system ?

**Comment by ashishchopra778** [comment]
Updated the path to **images** folder which should be in the same directory as compute_feature.py

**Comment by khalibartan** [comment]
@ashishchopra778 There is no **images folder** , Can you upload the images ?

**Comment by ashishchopra778** [comment]
Added the **images** folder. Copied the code to **download the data set** in images folder. Run that code to download the images to the same folder.
